#!/bin/bash
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi
echo""
echo "	 ▄████▄▓██   ██▓ ▄▄▄▄   ▓█████  ██▀███   ██▓███   ▄▄▄     ▄▄▄█████▓ ██▀███   ██▓ ▒█████  ▄▄▄█████▓"
echo "	▒██▀ ▀█ ▒██  ██▒▓█████▄ ▓█   ▀ ▓██ ▒ ██▒▓██░  ██▒▒████▄   ▓  ██▒ ▓▒▓██ ▒ ██▒▓██▒▒██▒  ██▒▓  ██▒ ▓▒"
echo "	▒▓█    ▄ ▒██ ██░▒██▒ ▄██▒███   ▓██ ░▄█ ▒▓██░ ██▓▒▒██  ▀█▄ ▒ ▓██░ ▒░▓██ ░▄█ ▒▒██▒▒██░  ██▒▒ ▓██░ ▒░"
echo "	▒▓▓▄ ▄██▒░ ▐██▓░▒██░█▀  ▒▓█  ▄ ▒██▀▀█▄  ▒██▄█▓▒ ▒░██▄▄▄▄██░ ▓██▓ ░ ▒██▀▀█▄  ░██░▒██   ██░░ ▓██▓ ░ "
echo "	▒ ▓███▀ ░░ ██▒▓░░▓█  ▀█▓░▒████▒░██▓ ▒██▒▒██▒ ░  ░ ▓█   ▓██▒ ▒██▒ ░ ░██▓ ▒██▒░██░░ ████▓▒░  ▒██▒ ░ "
echo "	░ ░▒ ▒  ░ ██▒▒▒ ░▒▓███▀▒░░ ▒░ ░░ ▒▓ ░▒▓░▒▓▒░ ░  ░ ▒▒   ▓▒█░ ▒ ░░   ░ ▒▓ ░▒▓░░▓  ░ ▒░▒░▒░   ▒ ░░   "
echo "	  ░  ▒  ▓██ ░▒░ ▒░▒   ░  ░ ░  ░  ░▒ ░ ▒░░▒ ░       ▒   ▒▒ ░   ░      ░▒ ░ ▒░ ▒ ░  ░ ▒ ▒░     ░    "
echo "	░       ▒ ▒ ░░   ░    ░    ░     ░░   ░ ░░         ░   ▒    ░        ░░   ░  ▒ ░░ ░ ░ ▒    ░      "
echo "	░ ░     ░ ░      ░         ░  ░   ░                    ░  ░           ░      ░      ░ ░           "
echo "	░       ░ ░           ░                                                                           "
echo""

mkdir /opt/scripts
cp /etc/ssh/sshd_config /opt/scripts/sshd_config.bak

sudo apt remove openssh-server -y > /dev/null
sudo apt purge openssh-server -y > /dev/null
sudo apt install openssh-server -y > /dev/null

rm /etc/ssh/ssh_config


